---
abstract: 'MANIFEST.SKIP Manangement for Modules'
author:
  - 'Ingy döt Net'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Module::Manifest::Skip
name: Module-Manifest-Skip
no_index:
  directory:
    - inc
    - share
    - t
requires:
  Moo: 0.091013
  perl: 5.8.3
resources:
  homepage: https://github.com/ingydotnet/module-manifest-skip-pm/tree
  license: http://dev.perl.org/licenses/
  repository:
    type: git
    url: git://github.com/ingydotnet/module-manifest-skip-pm.git
    web: https://github.com/ingydotnet/module-manifest-skip-pm/tree
version: 0.17
